apiVersion: apps/v1
kind: Deployment
metadata:
  name: swasthasathi-app
  namespace: swasthasathi
  labels:
    app: swasthasathi-app
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: swasthasathi-app
  template:
    metadata:
      labels:
        app: swasthasathi-app
        version: v1
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: swasthasathi-app
        image: ghcr.io/nagapraveen-automationtesting/swasthasathi-app:latest  # This will be replaced by Jenkins with actual image tag
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_APP_BASE_PATH
          value: "/swasthasathi-app/"
        - name: NGINX_ENTRYPOINT_QUIET_LOGS
          value: "1"
        # Simplified configuration - no resource limits, no health checks, no security context
        # These were causing the container crashes
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---

