apiVersion: apps/v1
kind: Deployment
metadata:
  name: swasthasathi-app
  namespace: swasthasathi
  labels:
    app: swasthasathi-app
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: swasthasathi-app
  template:
    metadata:
      labels:
        app: swasthasathi-app
        version: v1
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: swasthasathi-app
        image: ghcr.io/nagapraveen-automationtesting/swasthasathi-app:latest  # This will be replaced by Jenkins with actual image tag
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: VITE_APP_BASE_PATH
          value: "/swasthasathi-app/"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-tmp
          mountPath: /var/run
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-tmp
        emptyDir: {}
---

